# api document is available on http://localhost:5158/scalar/v1

POST http://localhost:5158/api/Meeting
Content-Type: application/json

{
  "roomId": 1,
  "status": "Active",
  "type": "InPerson",
  "title": "a interview session",
  "startDateTime": "2025-02-03T09:30:00+03:30",
  "endDateTime": "2025-02-03T10:30:00+03:30",
  "meetingUrl": null,
  "meetingMembers": [
    1,
    2
  ]
}

###

PUT http://localhost:5158/api/Meeting/Cancel?MeetingId=17

###

PUT http://localhost:5158/api/Meeting/SubmitResult?MeetingId=17
Content-Type: application/json

{
  "Result": "The session result"
}

###

POST http://localhost:5158/api/Meeting/IntelligenceAdd
Content-Type: application/json

{
  "roomId": 1,
  "status": "Active",
  "type": "InPerson",
  "title": "a interview session",
  "ElapsedMinute": "30",
  "meetingUrl": null,
  "meetingMembers": [
    1,
    2
  ]
}

###

PUT http://localhost:5158/api/Meeting?MeetingId=17
Content-Type: application/json

{
  "roomId": 1,
  "status": "Active",
  "type": "InPerson",
  "title": "a interview session222",
  "startDateTime": "2025-02-03T09:30:00+03:30",
  "endDateTime": "2025-02-03T10:30:00+03:30",
  "meetingUrl": null,
  "meetingMembers": [
    1,
    2
  ]
}

###